spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: java-mongo-skeleton-reactive
      username: user_name
      password: user_password
      auth-index-creation: true
